name: Publish plugin

on:
  workflow_dispatch:
  
jobs:
  build:

    runs-on: windows-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Download Dalamud
      run: |
        Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/net5/latest.zip -OutFile latest.zip
        Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev\"
          
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore
      
    - name: Create artifact
      run: |
        Compress-Archive -Path "bin/x64/Debug/*" -DestinationPath Plugin.zip
        
    - name: Get version date
      uses: 1466587594/get-current-time@v2
      id: version-date
      with:
        format: YYYY-MM-DD
        
    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        name: ${{ env.PROJECT_NAME }} ${{ steps.tag.outputs.tag }}
        tag_name: ${{ steps.tag.outputs.tag }}
        body: ${{ github.events.commits[0].message }}
        files: ${{ steps.download.outputs.download-path }}/Plugin.zip
        
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: "Plugin.zip"
        name: ${{ steps.version-date.outputs.formattedTime }}
        tag: v${{ steps.version-date.outputs.formattedTime }}
        #body: ${{ steps.Changelog.outputs.changelog }}
        draft: true
        token: ${{ secrets.GITHUB_TOKEN }}
