name: Publish plugin

on:
  workflow_dispatch:
  
jobs:
  build:

    runs-on: windows-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Download Dalamud
      run: |
        Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/net5/latest.zip -OutFile latest.zip
        Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev\"
          
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: .NET project version updater
      uses: vers-one/dotnet-project-version-updater@v1.0
      with:
        file: FullscreenToggle.sln
        version: 1.0.0.1
    
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
