name: Publish plugin

on:
  workflow_dispatch:
  
jobs:
  build:

    runs-on: windows-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Download Dalamud
      run: |
        Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/net5/latest.zip -OutFile latest.zip
        Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev\"
          
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore
      
    - name: Zip Release
      uses: TheDoctor0/zip-release@0.6.0
      with:
        filename: '../Plugin.zip'
        directory: './bin/x64/Debug/'
        exclusions: '*.pdb* *.xml*'
        
    - name: Get version date
      uses: 1466587594/get-current-time@v2
      id: version-date
      with:
        format: YYYY-MM-DD
        
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: "Plugin.zip"
        name: ${{ steps.version-date.outputs.formattedTime }}
        tag: v${{ steps.version-date.outputs.formattedTime }}
        #body: ${{ steps.Changelog.outputs.changelog }}
        draft: true
        token: ${{ secrets.GITHUB_TOKEN }}
